# -*- coding: utf-8 -*-
"""webscrapping(ipl data).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-ru2voubjYVMWkz6WvnsNCSrKofAIFb
"""

import requests
from bs4 import BeautifulSoup

url="https://www.iplt20.com/auction/2022"

r=requests.get(url)

print(r)

soup=BeautifulSoup(r.text,"lxml")

print(soup)

#<table class="ih-td-tab w-100 auction-tbl">

tab=soup.find("table",class_="ih-td-tab w-100 auction-tbl")

print(tab)

h_tag=tab.find_all("th")

h_tag

data=[]
for i in h_tag:
  data1=i.text
  data.append(data1)

print(data)

#rows,cols
rows=tab.find_all("tr")

rows

row=[]
for i in rows:
  rows=i.text
  row.append(rows.strip())

row

col=tab.find_all("td")
col

cols=[]
for i in col:
  col=i.text
  cols.append(col.strip())

cols

df=pd.DataFrame(columns=data)
df

###df['SR.NO']=
df['TEAM']=cols[1::5]
df['FUNDS REMAINING']=cols[2::5]
df['OVERSEAS PLAYERS ']=cols[3::5]
df['TOTAL PLAYERS']=cols[4::5]

df

import pandas as pd

df = pd.DataFrame({"SR.NO" : cols[0::5],
    "TEAM": cols[1::5],
    "FUNDS REMAINING": cols[2::5],
    "OVERSEAS PLAYERS": cols[3::5],
    "TOTAL PLAYERS": cols[4::5],

})

df

df.set_index('SR.NO', inplace=True)
df

df.to_csv('IPL_Auction_2022.csv')

